spring:
  application:
    name: api
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

api:
  security:
    token:
      secret: ${JWT_SECRET}